# not working with gpu
version: '3.8'
services:
  tokenizer:
    image: dig/tokenizer:latest
    container_name: tokenizer
    restart: always
    ports:
      - 5108:5108
    volumes:
      - tokenizer:/data/tokenizer
      - sudachipy-resources:/usr/local/lib/python3.7/dist-packages/sudachipy/resources
volumes:
  tokenizer:
    name: tokenizer
  sudachipy-resources:
    name: sudachipy-resources
