# not working with gpu
version: '3.8'
services:
  spacy:
    image: dig/spacy:latest
    container_name: spacy
    restart: always
    ports:
      - 5108:5108
    volumes:
      - nlp-data:/nlp-data
      - sudachipy-resources:/usr/local/lib/python3.7/dist-packages/sudachipy/resources
volumes:
  nlp-data:
    name: nlp-data
  sudachipy-resources:
    name: sudachipy-resources
